language: c
compiler: gcc
install: true
dist: trusty
sudo: required
addons: {
    apt: {
        sources: [
            ubuntu-toolchain-r-test
        ],
    packages: [
        "gcc-7"
    ]
    }
}
script:
  - sed -i -e s+'CC  = gcc.*'+'CC  = gcc-7'+g make/include_GCC.mk
  - make && sudo make install
  - /usr/local/bin/likwid-topology -c -C -g
  - /usr/local/bin/likwid-pin -p
  - sudo modprobe msr
  - ls -la /dev/cpu/*
  - ls -la /usr/local/sbin/*
  - make -C test streamGCC
  - /usr/local/bin/likwid-perfctr -i
  - /usr/local/bin/likwid-bench -t copy -w N:100MB:2
